apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crd_name }}
spec:
  conversion:
    strategy: None
  group: helmss.test
  names:
    kind: TestThing
    listKind: TestThingList
    plural: testthings
    singular: testthing
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  pattern: '^[[:alnum:]][a-z0-9-_\s]+[[:alnum:]]$'
                  maxLength: 30
                  description: The name of the thing
